# -*- coding: utf-8 -*-
"""HARVEST PLANNING SCHEDULE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g7FCdJU7ix6p2ImqUq2dor4bnWFET0Ga
"""

from datetime import datetime, timedelta


sowing_date = "2025-01-10"
days_to_maturity = 120
field_area = 10
daily_harvest_capacity = 2


sow_date = datetime.strptime(sowing_date, "%Y-%m-%d")

maturity_date = sow_date + timedelta(days=days_to_maturity)
harvest_days = field_area / daily_harvest_capacity
harvest_start = maturity_date
harvest_end = maturity_date + timedelta(days=harvest_days)


print("🌾 Harvest Planning Schedule")
print("----------------------------")
print("Sowing Date:", sow_date.date())
print("Maturity Date:", maturity_date.date())
print("Harvest Start:", harvest_start.date())
print("Harvest End:", harvest_end.date())
print("Total Harvest Days:", harvest_days)